# Generated by Django 3.1.1 on 2020-09-29 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_title', models.CharField(max_length=200)),
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_on', models.DateTimeField(default=datetime.datetime.now)),
                ('issuer_username', models.CharField(blank=True, editable=False, max_length=200)),
                ('issuer_email', models.EmailField(blank=True, editable=False, max_length=200)),
                ('project_type', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='LOW', max_length=20)),
                ('deadline', models.DateField(blank=True)),
                ('severity', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='LOW', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('issue_file', models.FileField(blank=True, upload_to='issues_file/%Y/%m/%d/')),
                ('issue_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVALID', 'Invalid')], default='ACTIVE', max_length=20)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_on', models.DateTimeField(blank=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('assigned_to_username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
