# Generated by Django 3.1.1 on 2020-09-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '00010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issuer_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
