# Generated by Django 3.1.1 on 2020-10-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20200929_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_email',
            field=models.EmailField(blank=True, editable=False, max_length=200),
        ),
    ]
