# Generated by Django 3.1.1 on 2020-10-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_auto_20201001_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
