# Generated by Django 3.1.1 on 2020-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_auto_20201001_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issuer_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
