# Generated by Django 3.1.1 on 2020-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_auto_20201001_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to_email',
            field=models.EmailField(default='not assigned to @ anyone yet', max_length=254),
        ),
    ]
