# Generated by Django 3.1.1 on 2020-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0021_auto_20201001_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
