# Generated by Django 3.1.1 on 2020-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0021_auto_20201001_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project_type',
        ),
        migrations.AddField(
            model_name='issue',
            name='enops',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
