# Generated by Django 3.1.1 on 2020-10-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0024_auto_20201008_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issueid',
            new_name='issue_id',
        ),
    ]
