# Generated by Django 3.1.1 on 2020-10-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0027_auto_20201008_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
