# Generated by Django 3.1.1 on 2020-10-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0031_auto_20201008_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_file',
            field=models.FileField(blank=True, upload_to='issues_file/%Y/%m/%d/'),
        ),
    ]
