# Generated by Django 3.1.1 on 2020-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0036_auto_20201008_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_file',
            field=models.URLField(blank=True),
        ),
    ]
