# Generated by Django 3.1.1 on 2020-10-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_prof_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prof_pic',
        ),
    ]
